name: labeled_text
description: A Flutter Widget to display Text with a custom label field.
version: 0.0.1
homepage: https://github.com/christian-leingang/labeled_textfield

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
